// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Taskbar → Primary*
 */
export interface TaskbarSliceDefaultPrimary {
  /**
   * labels field in *Taskbar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: taskbar.primary.labels
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  labels: prismic.RichTextField;
}

/**
 * Default variation for Taskbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TaskbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TaskbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Taskbar*
 */
type TaskbarSliceVariation = TaskbarSliceDefault;

/**
 * Taskbar Shared Slice
 *
 * - **API ID**: `taskbar`
 * - **Description**: Taskbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TaskbarSlice = prismic.SharedSlice<
  "taskbar",
  TaskbarSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      TaskbarSlice,
      TaskbarSliceDefaultPrimary,
      TaskbarSliceVariation,
      TaskbarSliceDefault,
    };
  }
}
